CREATE TABLE Doctor (
    ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Specialization VARCHAR2(100) NOT NULL,
    Experience NUMBER,
    Contact VARCHAR2(50),
    Email VARCHAR2(100)
);

CREATE TABLE Patient (
    ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Address VARCHAR2(200),
    Contact VARCHAR2(50),
    Email VARCHAR2(100)
);

CREATE TABLE Room (
    Numb NUMBER PRIMARY KEY,
    Type VARCHAR2(50) NOT NULL,
    Beds_avail NUMBER DEFAULT 1
);

CREATE TABLE Prescription (
    ID NUMBER PRIMARY KEY
);

CREATE TABLE Treatment (
    ID NUMBER PRIMARY KEY,
    Dat TIMESTAMP,
    Name VARCHAR2(100) NOT NULL,
    Dosage VARCHAR2(100),
    prescriptionID NUMBER,
    CONSTRAINT fk_prescription_treatment FOREIGN KEY (prescriptionID) REFERENCES Prescription(ID)
);

CREATE TABLE lab_tests (
    id NUMBER PRIMARY KEY,
    test_name VARCHAR2(100) NOT NULL,
    test_description VARCHAR2(500),
    test_date DATE DEFAULT SYSDATE,
    test_result VARCHAR2(100),
    prescription_id NUMBER,
    CONSTRAINT fk_prescription_lab FOREIGN KEY (prescription_id) REFERENCES prescription(id)
);

CREATE TABLE Admission (
    ID NUMBER PRIMARY KEY,
    Patient_ID NUMBER,
    Room_Number NUMBER,
    Admit_date TIMESTAMP,
    Discharge_date TIMESTAMP,
    CONSTRAINT fk_patient_admission FOREIGN KEY (Patient_ID) REFERENCES Patient(ID),
    CONSTRAINT fk_room_admission FOREIGN KEY (Room_Number) REFERENCES Room(Numb)
);

CREATE TABLE Appointment (
    ID NUMBER PRIMARY KEY,
    Prescription_ID NUMBER UNIQUE not null,
    Priority NUMBER,
    Patient_ID NUMBER,
    Doctor_ID NUMBER,
    Dat DATE,
    CONSTRAINT fk_prescription_appointment FOREIGN KEY (Prescription_ID) REFERENCES Prescription(ID),
    CONSTRAINT fk_patient_appointment FOREIGN KEY (Patient_ID) REFERENCES Patient(ID),
    CONSTRAINT fk_doctor_appointment FOREIGN KEY (Doctor_ID) REFERENCES Doctor(ID)
);

CREATE TABLE admins (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL
);